refactor(Dockerfile): streamline jlink options for better maintainability

diff --git a/alpine/Dockerfile b/alpine/Dockerfile
--- a/alpine/Dockerfile
+++ b/alpine/Dockerfile
@@ -43,30 +43,19 @@ RUN apk add --no-cache \
 
 ENV PATH="/opt/jdk-${JAVA_VERSION}/bin:${PATH}"
 
-RUN case "$(jlink --version 2>&1)" in \
-      "17."*) jlink \
-        --strip-java-debug-attributes \
-        --compress=2 \
-        --add-modules ALL-MODULE-PATH \
-        --no-man-pages \
-        --no-header-files \
-        --output /javaruntime ;; \
-      "21."*) jlink \
-        --strip-java-debug-attributes \
-        --compress=zip-6 \
-        --add-modules ALL-MODULE-PATH \
-        --no-man-pages \
-        --no-header-files \
-        --output /javaruntime ;; \
-      "25"*) jlink \
-        --strip-java-debug-attributes \
-        --compress=zip-6 \
-        --add-modules java.base,java.logging,java.xml,java.se \
-        --no-man-pages \
-        --no-header-files \
-        --output /javaruntime ;; \
-      *) echo "ERROR: unmanaged jlink version pattern" && exit 1 ;; \
-    esac
+RUN JLINK_COMMON_OPTS="--strip-java-debug-attributes --no-man-pages --no-header-files --output /javaruntime"; \
+  case "$(jlink --version 2>&1)" in \
+    "17."*) jlink $JLINK_COMMON_OPTS \
+      --compress=2 \
+      --add-modules ALL-MODULE-PATH ;; \
+    "21."*) jlink $JLINK_COMMON_OPTS \
+      --compress=zip-6 \
+      --add-modules ALL-MODULE-PATH ;; \
+    "25"*) jlink $JLINK_COMMON_OPTS \
+      --compress=zip-6 \
+      --add-modules java.base,java.logging,java.xml,java.se ;; \
+    *) echo "ERROR: unmanaged jlink version pattern" && exit 1 ;; \
+  esac
 
 FROM alpine:"${ALPINE_TAG}" AS build
 
